// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using SixLabors.ImageSharp.Textures.Astc.Core;

namespace SixLabors.ImageSharp.Textures.Astc.ColorEncoding;

internal sealed class Partition
{
    private static readonly System.Collections.Concurrent.ConcurrentDictionary<(Footprint, int, int), Partition> PartitionCache = new();

    public Partition(Footprint footprint, int partitionCount, int? id = null)
    {
        this.Footprint = footprint;
        this.PartitionCount = partitionCount;
        this.PartitionId = id;
        this.Assignment = [];
    }

    public Footprint Footprint { get; set; }

    public int PartitionCount { get; set; }

    public int? PartitionId { get; set; }

    public int[] Assignment { get; set; }

    public override bool Equals(object? obj)
    {
        if (obj is not Partition other)
        {
            return false;
        }

        return PartitionMetric(this, other) == 0;
    }

    public override int GetHashCode() => HashCode.Combine(this.Footprint, this.PartitionCount, this.PartitionId);

    public static int PartitionMetric(Partition a, Partition b)
    {
        ArgumentOutOfRangeException.ThrowIfNotEqual(a.Footprint, b.Footprint);

        const int MaxNumSubsets = 4;
        int width = a.Footprint.Width;
        int height = a.Footprint.Height;

        var pairCounts = new List<(int A, int B, int Count)>();
        for (int y = 0; y < 4; ++y)
        {
            for (int x = 0; x < 4; ++x)
            {
                pairCounts.Add((x, y, 0));
            }
        }

        for (int y = 0; y < height; ++y)
        {
            for (int x = 0; x < width; ++x)
            {
                int idx = (y * width) + x;
                int aVal = a.Assignment[idx];
                int bVal = b.Assignment[idx];
                pairCounts[(bVal * 4) + aVal] = (aVal, bVal, pairCounts[(bVal * 4) + aVal].Count + 1);
            }
        }

        var sorted = pairCounts.OrderByDescending(p => p.Count).ToList();
        var assigned = new bool[MaxNumSubsets, MaxNumSubsets];
        int pixelsMatched = 0;
        foreach (var pairCount in sorted)
        {
            bool isAssigned = false;
            for (int i = 0; i < MaxNumSubsets; ++i)
            {
                if (assigned[pairCount.A, i] || assigned[i, pairCount.B])
                {
                    isAssigned = true;
                    break;
                }
            }

            if (!isAssigned)
            {
                assigned[pairCount.A, pairCount.B] = true;
                pixelsMatched += pairCount.Count;
            }
        }

        return (width * height) - pixelsMatched;
    }

    // Basic GetASTCPartition implementation using selection function from C++
    public static Partition GetASTCPartition(Footprint footprint, int partitionCount, int partitionId)
    {
        var key = (footprint, partitionCount, partitionId);
        if (PartitionCache.TryGetValue(key, out var cached))
        {
            return cached;
        }

        var part = new Partition(footprint, partitionCount, partitionId);
        int w = footprint.Width;
        int h = footprint.Height;
        var assignment = new int[w * h];
        int idx = 0;
        for (int y = 0; y < h; ++y)
        {
            for (int x = 0; x < w; ++x)
            {
                assignment[idx++] = SelectASTCPartition(partitionId, x, y, 0, partitionCount, footprint.PixelCount);
            }
        }

        part.Assignment = assignment;
        PartitionCache.TryAdd(key, part);
        return part;
    }

    // For now, implement a naive FindClosestASTCPartition that just checks a
    // small set of candidate partitions generated by enum footprints. We'll
    // return the same footprint size partitions with ID=0 for simplicity.
    public static Partition FindClosestASTCPartition(Partition candidate)
    {
        // Search a few partitions and pick the one with minimal PartitionMetric
        var best = GetASTCPartition(candidate.Footprint, Math.Max(1, candidate.PartitionCount), 0);
        int bestDist = PartitionMetric(best, candidate);
        return best;
    }

    // Very small port of selection function; behavior taken from C++ file.
    private static int SelectASTCPartition(int seed, int x, int y, int z, int partitionCount, int pixelCount)
    {
        if (partitionCount <= 1)
        {
            return 0;
        }

        if (pixelCount < 31)
        {
            x <<= 1;
            y <<= 1;
            z <<= 1;
        }

        seed += (partitionCount - 1) * 1024;
        uint randomNumber = (uint)seed;
        randomNumber ^= randomNumber >> 15;
        randomNumber -= randomNumber << 17;
        randomNumber += randomNumber << 7;
        randomNumber += randomNumber << 4;
        randomNumber ^= randomNumber >> 5;
        randomNumber += randomNumber << 16;
        randomNumber ^= randomNumber >> 7;
        randomNumber ^= randomNumber >> 3;
        randomNumber ^= randomNumber << 6;
        randomNumber ^= randomNumber >> 17;

        uint seed1 = randomNumber & 0xF;
        uint seed2 = (randomNumber >> 4) & 0xF;
        uint seed3 = (randomNumber >> 8) & 0xF;
        uint seed4 = (randomNumber >> 12) & 0xF;
        uint seed5 = (randomNumber >> 16) & 0xF;
        uint seed6 = (randomNumber >> 20) & 0xF;
        uint seed7 = (randomNumber >> 24) & 0xF;
        uint seed8 = (randomNumber >> 28) & 0xF;
        uint seed9 = (randomNumber >> 18) & 0xF;
        uint seed10 = (randomNumber >> 22) & 0xF;
        uint seed11 = (randomNumber >> 26) & 0xF;
        uint seed12 = ((randomNumber >> 30) | (randomNumber << 2)) & 0xF;

        seed1 *= seed1;
        seed2 *= seed2;
        seed3 *= seed3;
        seed4 *= seed4;
        seed5 *= seed5;
        seed6 *= seed6;
        seed7 *= seed7;
        seed8 *= seed8;
        seed9 *= seed9;
        seed10 *= seed10;
        seed11 *= seed11;
        seed12 *= seed12;

        int sh1, sh2, sh3;
        if ((seed & 1) != 0)
        {
            sh1 = (seed & 2) != 0 ? 4 : 5;
            sh2 = (partitionCount == 3) ? 6 : 5;
        }
        else
        {
            sh1 = (partitionCount == 3) ? 6 : 5;
            sh2 = (seed & 2) != 0 ? 4 : 5;
        }

        sh3 = (seed & 0x10) != 0 ? sh1 : sh2;

        seed1 >>= sh1;
        seed2 >>= sh2;
        seed3 >>= sh1;
        seed4 >>= sh2;
        seed5 >>= sh1;
        seed6 >>= sh2;
        seed7 >>= sh1;
        seed8 >>= sh2;
        seed9 >>= sh3;
        seed10 >>= sh3;
        seed11 >>= sh3;
        seed12 >>= sh3;

        int a = (int)((seed1 * x) + (seed2 * y) + (seed11 * z) + (randomNumber >> 14));
        int b = (int)((seed3 * x) + (seed4 * y) + (seed12 * z) + (randomNumber >> 10));
        int c = (int)((seed5 * x) + (seed6 * y) + (seed9 * z) + (randomNumber >> 6));
        int d = (int)((seed7 * x) + (seed8 * y) + (seed10 * z) + (randomNumber >> 2));

        a &= 0x3F;
        b &= 0x3F;
        c &= 0x3F;
        d &= 0x3F;
        if (partitionCount <= 3)
        {
            d = 0;
        }

        if (partitionCount <= 2)
        {
            c = 0;
        }

        if (a >= b && a >= c && a >= d)
        {
            return 0;
        }
        else if (b >= c && b >= d)
        {
            return 1;
        }
        else if (c >= d)
        {
            return 2;
        }
        else
        {
            return 3;
        }
    }
}
